UNREAD_THRESHOLD = 2
ALERT_THRESHOLD = 6
OFFLINE_THRESHOLD = 15
INACTIVE_THRESHOLD = 604800
STATUS_UPDATE_THRESHOLD = 8
ITEMS_PER_PAGE = 15
MAX_KEYWORDS = 4

STATUS_ONLINE = 0
STATUS_OFFLINE = 1
STATUS_INACTIVE = 2

errors = {'random_peer_not_found' : "Could not found a random peer at the moment. Please try again in a minute."}

RATING_STEPS = 5
