from datetime import timedelta

OFFLINE_THRESHOLD = 15
INACTIVE_THRESHOLD = 604800
STATUS_UPDATE_THRESHOLD = 8

ITEMS_PER_PAGE = 15
MAX_SEARCH_KEYWORDS = 6
MAX_KEYWORDS = 100

STATUS_ONLINE = 0
STATUS_OFFLINE = 1
STATUS_INACTIVE = 2

RANDOM_CHAT_WAIT = 2

TOTAL_RESULTS = 100

AGE_INDEX_THRESHOLDS = {0 : timedelta(days = 2), 1 : timedelta(days = 9), 2 : timedelta(days = 40)}
AGE_INDEX_STEPS = len(AGE_INDEX_THRESHOLDS)

REQUEST_TIMESTAMP_PADDING = timedelta(seconds = 3)

OPEN_CHAT_THRESHOLD = timedelta(seconds = 3)
